#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Output\OutputInterface;

require 'vendor/autoload.php';

$app=new Application('My Demo Command', '0.1.1');

$app->register('sayhello')
	->setDescription('Offer a greeting to the given person')
	->addArgument('name', InputArgument::OPTIONAL, 'Your name.')
	->setCode(function(InputInterface $input, OutputInterface $output){
		$message='hello world '. $input->getArgument('name');
		$output->writeln("<info>{$message}</info>");
	});

$app->run();
